### PR TITLE
Minor fixes for compliance with common checkers

### PR DESCRIPTION
**Pull request by integral-dw**
Hi, 
I added a few minor touch-ups to shut up common checkers like `package-lint` and `flycheck`.
I also took the liberty of shortening the regexp a bit.

### CODE REVIEW

**Comment by TonCherAmi** [comment]
@integral-dw hey, thanks a lot! Regarding the regexp bit, it does serve a purpose - it makes sure that empty headings (e.g. `** `) do not turn invisible. I used to have it set up the way you suggest initially and it was pretty annoying to find invisible empty headings in unexpected places from time to time.

**Comment by integral-dw** [comment]
Ah, yeah, I get that.  In that case It's probably best to keep it that way.

**Comment by integral-dw** [comment]
Maybe it would be best then to search for the first non-whitespace character and stop at that.
How about `"^\\(\\*+ \\)\\s-*\\S-"`?

**Comment by TonCherAmi** [comment]
Yeah I agree, that seems like a good idea.

**Review by TonCherAmi — APPROVED** [review]
Thanks!

**Pull request merged**
